# Generated by Django 3.2.7 on 2021-12-01 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0002_alter_logitem_utime'),
    ]

    operations = [
        migrations.AddField(
            model_name='logitem',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='照片'),
        ),
    ]
